version: '3.8'

services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: funnycat
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server_container:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - mongodb_container
    command: go run cmd/main.go --reload
    # environment:
    #   - GIN_MODE=release

volumes:
  mongodb_data_container: