version: '3.8'

services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: funnycat
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server_container:
    image: music-server:1.0
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb_container
    command:
      - ./MusicAPI


volumes:
  mongodb_data_container: