version: '3.8'

services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: funnycat
    ports:
      - 27017:27018
    volumes:
      - mongodb_data_container:/data/db

  server_container:
    image: phaseant/music_api:1.0
    ports:
      - 8000:9000
    depends_on:
      - mongodb_container
    environment:
      - GIN_MODE=release

volumes:
  mongodb_data_container: