version: '3.5'

services:
  MusicDB:
    container_name: MusicDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=funnycat
      - POSTGRES_USER=admin
    image: postgres:15.2